src/main/java/org/chunsik/pq/email/service/EmailService.java
- 에러로그 e.printStackTrace(); 을 slf4j.Logger 사용으로 리팩토링
=> refactor: 에러로그 Logger 사용

src/main/java/org/chunsik/pq/feedback/controller/FeedbackController.java, src/main/java/org/chunsik/pq/feedback/dto/FeedbackDTO.java, src/main/java/org/chunsik/pq/feedback/model/Feedback.java, src/main/java/org/chunsik/pq/feedback/service/FeedbackService.java
- 피드백 API 리팩토링
- 로그인사용자와 비로그인사용자 식별해서 userId DB에 저장
- 엔티티 nullable = false 삭제
- PQ-73
=> refactor: 피드백 API 리팩토링

src/main/java/org/chunsik/pq/login/controller/OauthController.java
*OauthController의 kakaoCallback을 "https://qqqq.world"로 리다이렉트 하도록 수정
=> fix: OauthController의 kakaoCallback을 리다이렉트 형태로 수정

src/main/java/org/chunsik/pq/feedback/controller/FeedbackController.java, src/main/java/org/chunsik/pq/generate/controller/GenerateController.java, src/main/java/org/chunsik/pq/login/controller/ControllerExceptionHandler.java, src/main/java/org/chunsik/pq/shortenurl/controller/ShortenUrlController.java
- 정확한 예외 종류를 알 수 없는 부분에 sentry 캡쳐 추가
- 일반적인 예외처리 핸들러 추가
=> feat: sentry 모니터링 구축

src/main/java/org/chunsik/pq/login/controller/OauthController.java, src/main/java/org/chunsik/pq/login/dto/KakaoAccountResponseDto.java, src/main/java/org/chunsik/pq/login/dto/SignUpOrLoginDto.java, src/main/java/org/chunsik/pq/login/exception/KakaoJsonProcessingException.java, src/main/java/org/chunsik/pq/login/service/KakaoOAuthProvider.java, src/main/java/org/chunsik/pq/login/service/UserService.java
OAuth 컨트롤러 수정 및 서비스 수정
- OAuth 컨트롤러 경량화
- 로직이 잘 맞는지?
- 없음
=> Fix: OAuth 로그인 수정

src/main/java/org/chunsik/pq/shortenurl/manager/ShortenUrlManager.java
- "XXXXX" -> "/s/XXXXX" 로 수정
- 단축 url생성 결과 수정
- PQ-96
=> Fix: url 생성 결과 변경

src/main/java/org/chunsik/pq/generate/controller/GenerateController.java, src/main/java/org/chunsik/pq/generate/dto/CreateImageResponseDto.java, src/main/java/org/chunsik/pq/generate/dto/GenerateImageDTO.java, src/main/java/org/chunsik/pq/generate/dto/TicketResponseDTO.java, src/main/java/org/chunsik/pq/generate/service/GenerateService.java
Feat: 티켓 정보 조회 기능 구현
> 티켓 정보 조회 기능 구현과 티켓 생성시 티켓 id를 응답하도록 수정
> createImage의 id 응답 형식이 적절한지 봐주시면 감사하겠습니다. 
> getTicket의 로직에 이상이 없는지 봐주시면 감사하겠습니다.
=> Feat: 티켓 정보 조회 기능 구현

src/main/java/org/chunsik/pq/generate/controller/GenerateController.java, src/main/java/org/chunsik/pq/generate/dto/GenerateApiRequestDTO.java, src/main/java/org/chunsik/pq/generate/dto/GenerateImageDTO.java, src/main/java/org/chunsik/pq/generate/model/BackgroundImage.java, src/main/java/org/chunsik/pq/generate/model/Category.java, src/main/java/org/chunsik/pq/generate/model/Tag.java, src/main/java/org/chunsik/pq/generate/model/TagBackgroundImage.java, src/main/java/org/chunsik/pq/generate/repository/CategoryRepository.java, src/main/java/org/chunsik/pq/generate/repository/TagBackgroundImageRepository.java, src/main/java/org/chunsik/pq/generate/repository/TagRepository.java, src/main/java/org/chunsik/pq/generate/service/GenerateService.java, src/main/java/org/chunsik/pq/login/repository/UserRepository.java, src/main/java/org/chunsik/pq/model/User.java, src/main/java/org/chunsik/pq/s3/model/Ticket.java
- 로그인,비로그인 사용자 userId 저장 로직 변경
- 태그배경이미지 저장 로직 구현
- 엔티티,DTO 변경
- 엔드포인트 변경
- 충돌나는 부분
=> Feat: userId로직 수정, 태그배경이미지 테이블로직 구현

src/main/java/org/chunsik/pq/generate/dto/GenerateApiRequestDTO.java, src/main/java/org/chunsik/pq/generate/dto/GenerateResponseDTO.java, src/main/java/org/chunsik/pq/generate/manager/OpenAIManager.java, src/main/java/org/chunsik/pq/generate/service/GenerateService.java
> 배경 이미지 생성 로직 수정
티켓 이미지 생성 로직 수정
GenerateResponseDTO 필드 변경
GenerateApiRequestDTO 필드 변경
generateImage 리턴 타입 String으로 변경
> 배경 이미지 생성 로직에 이상이 없는지
> 변경된 DTO의 필드들이 적절하게 변경됐는지
=> Fix: 배경 이미지 생성 로직 수정

src/main/java/org/chunsik/pq/email/service/EmailService.java, src/main/java/org/chunsik/pq/generate/exception/ErrorCode.java
Chore: logger, getter 수정
- e.printstacktrace 수정안된거 logger로 수정
- getter 사용 안한부분 수정
=> Chore: logger, getter 수정

src/main/java/org/chunsik/pq/feedback/service/FeedbackService.java, src/main/java/org/chunsik/pq/generate/service/GenerateService.java, src/main/java/org/chunsik/pq/login/controller/UserController.java, src/main/java/org/chunsik/pq/login/dto/MeResponseDto.java, src/main/java/org/chunsik/pq/login/manager/UserManager.java, src/main/java/org/chunsik/pq/login/security/CustomUserDetails.java, src/main/java/org/chunsik/pq/login/service/UserService.java
- UserManager 에 로그인 사용자 함수 응집
- /users/me 추가
- 
- UserManager 코드
- UserManager.currentUser() 사용하는 방식 확인 부탁드립니다.
=> Feat: mypage API 추가

src/main/java/org/chunsik/pq/feedback/model/Feedback.java, src/main/java/org/chunsik/pq/feedback/service/FeedbackService.java, src/main/java/org/chunsik/pq/generate/model/BackgroundImage.java, src/main/java/org/chunsik/pq/generate/model/Category.java, src/main/java/org/chunsik/pq/generate/model/Tag.java, src/main/java/org/chunsik/pq/generate/model/TagBackgroundImage.java, src/main/java/org/chunsik/pq/generate/service/GenerateService.java, src/main/java/org/chunsik/pq/login/dto/MeResponseDto.java, src/main/java/org/chunsik/pq/login/security/CustomUserDetails.java, src/main/java/org/chunsik/pq/login/service/UserService.java, src/main/java/org/chunsik/pq/model/User.java, src/main/java/org/chunsik/pq/s3/model/Ticket.java
Chore: entity의 id 타입 Long으로 변경
- entity의 id 타입 Long으로 변경
=> Chore: entity의 id 타입 Long으로 변경

.github/workflows/main-deploy.yml
> 변경된 부분을 짧게 요약해주세요.   
Sentry 빌드 추가, yaml 수정
=> Fix: main cicd

.github/workflows/main-deploy.yml
- var settings
- deployment jar s3 path
- 없음
- 없음
=> Fix: Main 배포 수정

src/main/resources/application-prod.yml
- `forward-headers-strategy: NATIVE` 추가
- Whatap에서 오류가 발생하는데 어떤 오류인지 모르겠습니다. ㅠ
=> HotFix: SSL 에러로 yaml 수정

src/main/java/org/chunsik/pq/generate/repository/BackgroundImageRepositoryImpl.java
=> Fix: categoryName으로 필터링할때 오류나는 버그 수정

src/main/java/org/chunsik/pq/gallery/repository/UserLikeRepository.java, src/main/java/org/chunsik/pq/generate/repository/TagBackgroundImageRepository.java, src/main/java/org/chunsik/pq/generate/repository/TagRepository.java, src/main/java/org/chunsik/pq/mypage/controller/MyPageController.java, src/main/java/org/chunsik/pq/mypage/dto/MyPQResponseDto.java, src/main/java/org/chunsik/pq/mypage/service/MyPageService.java, src/main/java/org/chunsik/pq/s3/repository/TicketRepository.java
- 나의 4Q API 응답 데이터 추가
- 태그정보 매핑
- TicketRepository 쿼리 로직
- 커밋에 상세내용 정리
- PQ-27 - PQ-53 - PQ-115
=> Feat: 나의 4Q 리스트 응답에 태그명, 배경이미지 좋아요 개수 정보 추가

src/main/java/org/chunsik/pq/generate/repository/BackgroundImageRepositoryImpl.java, src/main/java/org/chunsik/pq/mypage/controller/MyPageController.java
- 내가 좋아요한 4Q 응답 구현
- 로직과 응답 데이터는 갤러리 페이지 이미지 요청과 페이지네이션만 제외하고 동일하게 작성했습니다.
- PQ-27 - PQ-38
=> Feat: 마이페이지 내가 좋아요한 4Q 응답 구현

src/main/java/org/chunsik/pq/login/controller/AuthController.java, src/main/java/org/chunsik/pq/login/controller/OauthController.java, src/main/java/org/chunsik/pq/login/controller/UserController.java, src/main/java/org/chunsik/pq/login/dto/AccessTokenResponseDto.java, src/main/java/org/chunsik/pq/login/dto/AccessTokenWithExpirationDto.java, src/main/java/org/chunsik/pq/login/dto/JoinDto.java, src/main/java/org/chunsik/pq/login/dto/TokenDto.java, src/main/java/org/chunsik/pq/login/security/JwtTokenProvider.java, src/main/java/org/chunsik/pq/login/service/UserService.java
- login response 수정
- login service DTO 수정
- 간단한 수정 사항인데 사이드 이펙트가 발생하지 않을 지
- PQ-132
=> Feat: 로그인 만료 시간 Response 추가

src/main/java/org/chunsik/pq/generate/controller/GenerateController.java, src/main/java/org/chunsik/pq/generate/exception/UnauthorizedException.java, src/main/java/org/chunsik/pq/generate/repository/TagRepository.java, src/main/java/org/chunsik/pq/generate/repository/TagRepositoryCustom.java, src/main/java/org/chunsik/pq/generate/repository/TagRepositoryCustomImpl.java, src/main/java/org/chunsik/pq/generate/service/TagService.java
- 이전에 사용했던 태그 API
- 새로 추가한 클래스 이름과 위치가 적절한지
- 태그가져오는 로직
- PQ-6 - PQ-135
=> Feat: 이전에 사용했던 태그 구현

src/main/java/org/chunsik/pq/feedback/service/FeedbackService.java
> 피드백 DB에 저장되면 sentry에도 피드백 내용 보내주도록 했습니다.
> 코드가 길지않아서 다봐도 괜찮을 것 같습니다.
> PQ-142
=> Feat: 센트리로 피드백 내용 보내기

README.md
=> chore: README.md 업데이트

build.gradle, src/main/java/org/chunsik/pq/common/aspect/ExecutionTimeAspect.java, src/main/java/org/chunsik/pq/generate/repository/BackgroundImageRepositoryCustom.java, src/main/java/org/chunsik/pq/generate/service/BackgroundImageService.java, src/main/java/org/chunsik/pq/mypage/controller/MyPageController.java
> Spring AOP 사용하여 service 클래스 속도 측정후 로그 출력 및 prometheus로 수집
> 서비스를 안 거치는 api가 있어서 코드수정
> 요구사항에 맞게 잘 작성되었는지 확인해주세요
> PQ-145
=> Feat: AOP 실행시간 측정 및 모니터링
